const apiKey = "bf4c98ecfc269cd7a37e93dc80d3098f";

const requests = {
    fetchTrending: `/trending/all/week?api_key=${apiKey}&language=en-US`
}

export default requests;




/*tvshows and films organized by category
PARA VER EN UN PUENTE
OCTUBRE: MES DEL CINE ESPAÑOL (CINES EN ESPAÑOL)
CUENTA ATRÁS PARA HALLOWEEN
TENDENCIAS
TOP 30 SERIES
TOP 30 PELICULAS
THRILLERS
PELI DE TARDE
EXITOS TAQUILLA
AÑADIDOS RECIENTEMENTE
PERFECTAS PARA EMPEZAR
30 JOYAS OCULTAS
CINE EN FAMILIA
ACCIÓN
COMEDIA ROMÁNTICA
MUJERES PROTAGONISTAS
NOSTALGIA VHS
DOCUMENTALES
HBO ORIGINALS
*/